### PR TITLE
Fix postgresl data perms

### PR DESCRIPTION
**Pull request by huats**
Signed-off-by: Christophe Sauthier <christophe.sauthier@gmail.com>

### CODE REVIEW

**Review by jfelten — CHANGES_REQUESTED** [review]
Thank you! Looks good, but can you specify a tag for the busybox image? Ex busybox:1.32.0? Latest will cause k8s to always pull the image.

**Comment by huats** [comment]
I have fixed that, let's hope it is correctly pushed in the branch...

**Review by jfelten — APPROVED** [review]
LGTM - Since your PR is coming from a fork github is issuing a pull_request webhook event instead of a push event meaning the pipeline isn't going to work right now :(. I will fix this for future PRs. Thanks again.

**Comment by huats** [comment]
Great Thanks !
You'd have preferred that I create a branch in your repo instead to do the PR ?

**Pull request merged**
