### PR TITLE
Adding the podAnnotations to the Gitea pod.

### LINKED ISSUE #66: Add podAnnotations to the deployment
There seems to be a podAnnotations field in the chart values.yaml but it is not used in the deployment template.

It should apply the podAnnotations on the pods via placing it in the pod template of the deployment.

### PR DESCRIPTION
**Pull request by asoltesz**
The podAnnotations field was already defined in values.yaml but not utilized in the templates.

Fixes #66

### CODE REVIEW

**Comment by jfelten** [comment]
please bump version - otherwise looks good.

**Review by jfelten — CHANGES_REQUESTED** [review]
please bump version

**Comment by asoltesz** [comment]
Raised bugfix version since base field was already in only it was not used.

**Comment by jfelten** [comment]
Please refresh from  the main repo master and bump version one more time. There was an issue with the ci pipleine that should be fixed now. Sorry about that - still debugging the new pipeline.

**Comment by jfelten** [comment]
thank you for the PR!

**Pull request merged**
