### PR TITLE
Correct errors related to broken configs paths by adding gitea to the…

### PR DESCRIPTION
**Pull request by pecastro**
Noticed this issue while doing fresh deploys from the current values images to some of the most recent ones.

### CODE REVIEW

**Comment by jfelten** [comment]
Why the need to change these paths? Main concerns are:

    This is a breaking change since existing installs persist in the old path structure. Not necessarily opposed to changing it, but there needs to be a strong reason.
    The existing paths while not standard align more closely with the out of the box config.

I would rather address this by adding more flexible storage config if your install needs this.

**Comment by pecastro** [comment]
If you inspect the commit log message you'll see one of the errors I went through whilst trying to instantiate a fresh deploy of gitea.
That was not the only one, I've hit pretty much all of the paths that I've changed and they manifest themselves lazily, e.g. not at startup time.

My values file is pretty dull and other than that I'm using your chart to deploy it.
```
images:
  gitea: "gitea/gitea:1.12.4"
  memcached: "memcached:1.5.19-alpine"

## cache settings
memcached:
  maxItemMemory: 64
  verbosity: v
  extendedOptions: modern

service:
  http:
    serviceType: LoadBalancer
    port: 3000
    externalHost: gitea.wormholenet.local
  ssh:
    serviceType: LoadBalancer
    port: 22
    externalHost: gitea.wormholenet.local

persistence:
  enabled: true
  # giteaSize: 10Gi
  # postgresSize: 5Gi
  # storageClass: default
  # accessMode: ReadWriteMany
  # annotations:
  #   "helm.sh/resource-policy": keep
  existingGiteaClaim: my-gitea-gitea
  existingPostgresClaim: my-gitea-postgres

resources:
  gitea:
    requests:
      memory: 4Gi
      cpu: 2
    limits:
      memory: 25Gi
      cpu: 4
  postgres:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 1
  memcached:
    requests:
      memory: 64Mi
      cpu: 50m
```

I'm not sure if this issue is a byproduct of the absolute path fixes in fa36579bcccefe9dcd73ca376fe8375f4881d943.

_Directory listing from inside the container_
```bash-5.0# ls -altr /data/
total 20
drwxr-xr-x    5 root     root          4096 Dec  1 23:54 .
drwx------    2 root     root          4096 Dec  1 23:54 ssh
drwxr-xr-x    6 git      git           4096 Dec  1 23:56 gitea
drwxr-xr-x    1 root     root          4096 Dec  2 19:36 ..
drwxr-xr-x    4 git      git           4096 Dec  2 19:36 git
```

Furthermore, */etc/s6/gitea/setup* only cares about setting up the above dirs, so, without amending those paths it won't work properly.

**Comment by jfelten** [comment]
It likely is a byproduct of fa36579. That PR was a fix for data paths not being persisted properly. Prior to this any directory paths not in absolute /data path would not be persisted. What I am confused about is why this affected you. Did you manually edit the app.ini in the container at some point? That is the only thing I can think since your values look standard. Getting back to resolving this PR I would prefer to add a persistenc.static parameter in the values.yaml that can used to override the data path values, since most of your changes are changing paths fro, /data to /data/gitea. Would you be open to that?

**Comment by pecastro** [comment]
It turns out this is actually related with running the chart on Minikube and an apparent long standing issue regarding the use of hostpaths when configuring PV's.

**Pull request closed without merging**
